# Generated by Django 3.2 on 2023-05-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='created_on',
        ),
    ]
