# Generated by Django 3.2 on 2023-05-16 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_designer_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
