# Generated by Django 3.2 on 2023-05-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_designer_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='created_on',
        ),
    ]
