# Generated by Django 3.2 on 2023-06-06 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230606_0637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('date_created',)},
        ),
        migrations.AddField(
            model_name='customise',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
