# Generated by Django 3.2 on 2023-06-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customise',
            name='color',
            field=models.CharField(choices=[('none', 'none'), ('beign', 'beign'), ('burgundy', 'burgundy'), ('red', 'red'), ('nude', 'nude')], max_length=150),
        ),
        migrations.AlterField(
            model_name='customise',
            name='sole',
            field=models.CharField(choices=[('none', 'none'), ('platform', 'platform'), ('wedge heels', 'wedge heels')], max_length=150),
        ),
        migrations.AlterField(
            model_name='customise',
            name='special_size',
            field=models.CharField(choices=[('none', 'none'), ('UK 3', 'UK 3'), ('UK 3.5', 'UK 3.5'), ('UK 4', 'UK 4'), ('UK 4.5', 'UK 4.5'), ('UK 5', 'UK 5'), ('UK 5.5', 'UK 5.5'), ('UK 6', 'UK 6'), ('UK 6.5', 'UK 6.5'), ('UK 7', 'UK 7'), ('UK 7.5', 'UK 7.5'), ('UK 8', 'UK 8'), ('UK 8.5', 'UK 8.5'), ('UK 9', 'UK 9'), ('UK 9.5', 'UK 9.5')], max_length=150),
        ),
    ]
