# Generated by Django 3.2 on 2023-05-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230505_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='is_customized',
        ),
    ]
