# Generated by Django 3.2 on 2023-05-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_designer_created_on'),
        ('products', '0007_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='designer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.designer'),
        ),
    ]
