# Generated by Django 3.2 on 2023-05-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_is_customized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_customized',
        ),
    ]
