# Generated by Django 3.2 on 2023-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_is_customized'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_customised',
            field=models.BooleanField(default=False),
        ),
    ]
