# Generated by Django 3.2 on 2023-05-22 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_customise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customise',
            name='customised_value',
        ),
        migrations.AddField(
            model_name='customise',
            name='customised_value_color',
            field=models.CharField(choices=[('beign', 'beign'), ('burgundy', 'burgundy'), ('red', 'red'), ('nude', 'nude')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customise',
            name='customised_value_logo',
            field=models.BooleanField(choices=[('yes', 'yes'), ('no', 'no')], default=False),
        ),
        migrations.AddField(
            model_name='customise',
            name='customised_value_sole',
            field=models.CharField(choices=[('platform', 'platform'), ('wedge heels', 'wedge heels')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customise',
            name='customised_value_special_size',
            field=models.CharField(choices=[('UK 3', 'UK 3'), ('UK 3.5', 'UK 3.5'), ('UK 9', 'UK 9'), ('UK 9', 'UK 9')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
