# Generated by Django 3.2 on 2023-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20230522_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customise',
            name='customised_category',
        ),
        migrations.AlterField(
            model_name='customise',
            name='customised_value_logo',
            field=models.BooleanField(default=False),
        ),
    ]
