# Generated by Django 3.2 on 2023-05-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_name',
        ),
    ]
