# Generated by Django 3.2 on 2023-05-31 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0019_remove_product_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customise',
            name='custom_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customise',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
