# Generated by Django 3.2 on 2023-05-31 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('products', '0020_auto_20230531_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customise',
            name='custom_name',
        ),
        migrations.AddField(
            model_name='customise',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_name', to='user_profile.userprofile'),
        ),
    ]
