# Generated by Django 3.2 on 2023-05-31 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0021_auto_20230531_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customise',
            name='profile',
        ),
        migrations.AddField(
            model_name='customise',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customise',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
