# Generated by Django 3.2 on 2023-05-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20230531_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='customise',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customise',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
