# Generated by Django 3.2 on 2023-05-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20230531_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='customise',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
