# Generated by Django 3.2 on 2023-06-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_customise_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customise',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customise',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
