# Generated by Django 3.2 on 2023-06-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20230601_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customise',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customise',
            name='last_name',
        ),
    ]
